//! Build script - selects the linker memory layout and writes it into OUT_DIR
//! as `memory.x` so cortex-m-rt's `link.x` (`INCLUDE memory.x`) finds it. The
//! written file starts with the pairing storage bounds from `src/config.rs`,
//! which `memory_sd.x` checks its FLASH region against.
//!
//! IMPORTANT: the source layouts are intentionally NOT named `memory.x`. The
//! linker (rust-lld) resolves `INCLUDE memory.x` from the current directory
//! (the crate root) *before* the `-L` search path, so a `memory.x` in the root
//! would shadow the one we copy here and silently win — which previously made
//! the SoftDevice-free `sim` build link at the SoftDevice offset. Keeping the
//! sources as `memory_sd.x` / `memory_sim.x` ensures OUT_DIR/memory.x is the
//! only `memory.x` and is always the one used.
//!
//! It also passes the build's identity to the crate (`src/diagnostics.rs`),
//! which the firmware logs at boot: the git commit, the Cargo profile, and the
//! `DEFMT_LOG` filter.

#![allow(
    clippy::unwrap_used,
    reason = "a build script reports failure by panicking, which stops the build"
)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

// The firmware's constants, compiled here too so the linker script and the
// pairing store read the storage pages from one place.
#[allow(dead_code)]
#[path = "src/config.rs"]
mod config;

fn main() {
    // These modes have different vector-table origins and critical-section
    // implementations. Never silently link real firmware with the sim layout.
    assert!(
        !(env::var_os("CARGO_FEATURE_SIM").is_some()
            && env::var_os("CARGO_FEATURE_EMBEDDED").is_some()),
        "features `embedded` and `sim` are mutually exclusive; build each separately"
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // The SoftDevice-free `sim` build (Renode) owns the whole device, so it uses
    // a different memory map than the real firmware (which reserves the
    // SoftDevice flash/RAM region). Pick the right source layout by feature.
    let mem_file = if env::var_os("CARGO_FEATURE_SIM").is_some() {
        "memory_sim.x"
    } else {
        "memory_sd.x"
    };

    // Write the chosen layout to OUT_DIR as `memory.x`, preceded by the pairing
    // storage bounds from `config.rs`. `memory_sd.x` asserts that its FLASH
    // region ends where storage starts, so changing either side alone fails
    // the link instead of letting code land on pages the store erases.
    let layout = fs::read_to_string(mem_file).unwrap();
    let memory_x = format!(
        "/* Generated by build.rs from {mem_file} and src/config.rs. */\n\
         __bt2usb_storage_start = {:#010X};\n\
         __bt2usb_storage_end = {:#010X};\n\n\
         {layout}",
        config::STORAGE_FLASH_START,
        config::STORAGE_FLASH_END,
    );
    fs::write(out_dir.join("memory.x"), memory_x).unwrap();

    // Tell cargo to look for linker scripts in OUT_DIR.
    println!("cargo:rustc-link-search={}", out_dir.display());

    // Rebuild if either source layout changes...
    println!("cargo:rerun-if-changed=memory_sd.x");
    println!("cargo:rerun-if-changed=memory_sim.x");
    println!("cargo:rerun-if-changed=src/config.rs");
    println!("cargo:rerun-if-changed=build.rs");
    // ...and, crucially, re-run when the `sim` feature toggles, otherwise cargo
    // would reuse a previously-copied memory.x with the wrong layout.
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_SIM");

    // The build's identity for the boot log (`src/diagnostics.rs`).
    println!("cargo:rustc-env=BT2USB_SOURCE_COMMIT={}", source_commit());
    println!(
        "cargo:rustc-env=BT2USB_BUILD_PROFILE={}",
        env::var("PROFILE").unwrap()
    );
    println!("cargo:rerun-if-env-changed=DEFMT_LOG");
    let log_filter = env::var("DEFMT_LOG").unwrap_or_else(|_| "unset".into());
    println!("cargo:rustc-env=BT2USB_DEFMT_LOG={log_filter}");
}

/// The commit the firmware was built from, as the boot log reports it: the
/// checkout's `HEAD` with `-dirty` when tracked files differ from it (the
/// test `scripts/release.py` applies), else `BT2USB_SOURCE_COMMIT` for a build
/// outside git, else `unknown`.
///
/// The script reruns when `HEAD` moves (a checkout or a commit) and when a
/// firmware source changes, so the flag follows edits to the code it builds;
/// a change only to other tracked files, such as the documents, leaves the
/// flag from the last run.
fn source_commit() -> String {
    println!("cargo:rerun-if-env-changed=BT2USB_SOURCE_COMMIT");
    for source in ["src", "vendor", "Cargo.toml", "Cargo.lock", ".cargo"] {
        println!("cargo:rerun-if-changed={source}");
    }
    let Some(commit) = git(&["rev-parse", "HEAD"]).filter(|c| is_full_commit(c)) else {
        return match env::var("BT2USB_SOURCE_COMMIT") {
            Ok(commit) => {
                assert!(
                    is_full_commit(&commit),
                    "BT2USB_SOURCE_COMMIT must be a full 40-digit lower-case commit"
                );
                commit
            }
            Err(_) => "unknown".into(),
        };
    };
    // `HEAD` names the branch, whose ref moves on a commit; a packed ref
    // lives in `packed-refs`. Watch only the files that exist: Cargo reruns
    // the script on every build for a missing one.
    let branch = git(&["symbolic-ref", "-q", "HEAD"]);
    let watched = ["HEAD", branch.as_deref().unwrap_or("HEAD"), "packed-refs"];
    for name in watched {
        if let Some(path) = git(&["rev-parse", "--git-path", name]) {
            if Path::new(&path).exists() {
                println!("cargo:rerun-if-changed={path}");
            }
        }
    }
    // `--no-optional-locks` keeps `git status` from rewriting the index.
    let changes = git(&[
        "--no-optional-locks",
        "status",
        "--porcelain",
        "--untracked-files=no",
    ]);
    match changes {
        Some(changes) if changes.is_empty() => commit,
        _ => format!("{commit}-dirty"),
    }
}

/// Runs git in the crate root and returns its trimmed output, or `None` when
/// git is missing or fails.
fn git(args: &[&str]) -> Option<String> {
    let output = Command::new("git").args(args).output().ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout)
        .ok()
        .map(|text| text.trim().to_owned())
}

fn is_full_commit(text: &str) -> bool {
    text.len() == 40 && text.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}
