//! Build script - selects the linker memory layout and writes it into OUT_DIR
//! as `memory.x` so cortex-m-rt's `link.x` (`INCLUDE memory.x`) finds it. The
//! written file starts with the pairing storage bounds from `src/config.rs`,
//! which `memory_sd.x` checks its FLASH region against.
//!
//! IMPORTANT: the source layouts are intentionally NOT named `memory.x`. The
//! linker (rust-lld) resolves `INCLUDE memory.x` from the current directory
//! (the crate root) *before* the `-L` search path, so a `memory.x` in the root
//! would shadow the one we copy here and silently win — which previously made
//! the SoftDevice-free `sim` build link at the SoftDevice offset. Keeping the
//! sources as `memory_sd.x` / `memory_sim.x` ensures OUT_DIR/memory.x is the
//! only `memory.x` and is always the one used.

use std::env;
use std::fs;
use std::path::PathBuf;

// The firmware's constants, compiled here too so the linker script and the
// pairing store read the storage pages from one place.
#[allow(dead_code)]
#[path = "src/config.rs"]
mod config;

fn main() {
    // These modes have different vector-table origins and critical-section
    // implementations. Never silently link real firmware with the sim layout.
    assert!(
        !(env::var_os("CARGO_FEATURE_SIM").is_some()
            && env::var_os("CARGO_FEATURE_EMBEDDED").is_some()),
        "features `embedded` and `sim` are mutually exclusive; build each separately"
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // The SoftDevice-free `sim` build (Renode) owns the whole device, so it uses
    // a different memory map than the real firmware (which reserves the
    // SoftDevice flash/RAM region). Pick the right source layout by feature.
    let mem_file = if env::var_os("CARGO_FEATURE_SIM").is_some() {
        "memory_sim.x"
    } else {
        "memory_sd.x"
    };

    // Write the chosen layout to OUT_DIR as `memory.x`, preceded by the pairing
    // storage bounds from `config.rs`. `memory_sd.x` asserts that its FLASH
    // region ends where storage starts, so changing either side alone fails
    // the link instead of letting code land on pages the store erases.
    let layout = fs::read_to_string(mem_file).unwrap();
    let memory_x = format!(
        "/* Generated by build.rs from {mem_file} and src/config.rs. */\n\
         __bt2usb_storage_start = {:#010X};\n\
         __bt2usb_storage_end = {:#010X};\n\n\
         {layout}",
        config::STORAGE_FLASH_START,
        config::STORAGE_FLASH_END,
    );
    fs::write(out_dir.join("memory.x"), memory_x).unwrap();

    // Tell cargo to look for linker scripts in OUT_DIR.
    println!("cargo:rustc-link-search={}", out_dir.display());

    // Rebuild if either source layout changes...
    println!("cargo:rerun-if-changed=memory_sd.x");
    println!("cargo:rerun-if-changed=memory_sim.x");
    println!("cargo:rerun-if-changed=src/config.rs");
    println!("cargo:rerun-if-changed=build.rs");
    // ...and, crucially, re-run when the `sim` feature toggles, otherwise cargo
    // would reuse a previously-copied memory.x with the wrong layout.
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_SIM");
}
