//! Keeps `renode/oled-font-6x10.txt` equal to the font the firmware draws OLED
//! text in (`FONT_6X10` from embedded-graphics). The Renode SSD1306 model
//! (`renode/ssd1306.cs`) reads the screen's text back with that glyph table,
//! so a font change would otherwise break the simulation's screen checks.
//! After a font change, rewrite the table with
//! `UPDATE_OLED_FONT=1 cargo test --locked --test oled_font`.

use std::fmt::Write as _;

use embedded_graphics::mono_font::ascii::FONT_6X10;
use embedded_graphics::mono_font::MonoTextStyle;
use embedded_graphics::pixelcolor::BinaryColor;
use embedded_graphics::prelude::*;
use embedded_graphics::text::{Baseline, Text};

const WIDTH: usize = 6;
const HEIGHT: usize = 10;
const TABLE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/renode/oled-font-6x10.txt");

/// One character cell the glyph is drawn into.
struct Cell([[bool; WIDTH]; HEIGHT]);

impl OriginDimensions for Cell {
    fn size(&self) -> Size {
        Size::new(WIDTH as u32, HEIGHT as u32)
    }
}

impl DrawTarget for Cell {
    type Color = BinaryColor;
    type Error = core::convert::Infallible;

    fn draw_iter<I: IntoIterator<Item = Pixel<BinaryColor>>>(
        &mut self,
        pixels: I,
    ) -> Result<(), Self::Error> {
        for Pixel(point, color) in pixels {
            let (x, y) = (point.x as usize, point.y as usize);
            if x < WIDTH && y < HEIGHT {
                self.0[y][x] = color.is_on();
            }
        }
        Ok(())
    }
}

/// Each printable ASCII glyph as its ten rows from the top, each row a 6-bit
/// value whose bit 5 is the leftmost pixel.
fn table() -> String {
    let mut out = String::from(
        "# The firmware's OLED font, FONT_6X10 from embedded-graphics 0.8, for the\n\
         # Renode SSD1306 model's text reader (renode/ssd1306.cs). Generated by\n\
         # tests/oled_font.rs: rewrite it with\n\
         # `UPDATE_OLED_FONT=1 cargo test --locked --test oled_font`.\n\
         # One glyph per line: the character code, then its 10 rows from the top,\n\
         # each a 6-bit value whose bit 5 is the leftmost pixel.\n",
    );
    let style = MonoTextStyle::new(&FONT_6X10, BinaryColor::On);
    for code in 0x20u8..=0x7E {
        let mut cell = Cell([[false; WIDTH]; HEIGHT]);
        let glyph = [code];
        let text = core::str::from_utf8(&glyph).expect("printable ASCII");
        let _ = Text::with_baseline(text, Point::zero(), style, Baseline::Top).draw(&mut cell);
        let _ = write!(out, "{code:02x}");
        for row in cell.0 {
            let bits = row.iter().fold(0u8, |bits, &on| (bits << 1) | u8::from(on));
            let _ = write!(out, " {bits:02x}");
        }
        out.push('\n');
    }
    out
}

#[test]
fn the_font_has_the_cell_the_layout_and_the_text_reader_assume() {
    // ui::layout places lines by their baseline, 7 pixels below the top of a
    // 10-pixel cell; the text reader steps across the panel in 6-pixel cells.
    assert_eq!(FONT_6X10.character_size, Size::new(6, 10));
    assert_eq!(FONT_6X10.character_spacing, 0);
    assert_eq!(FONT_6X10.baseline, 7);
    // The table checks nothing unless the display draws in this same font.
    let display = include_str!("../src/ui/display.rs");
    assert!(display.contains("MonoTextStyle::new(&FONT_6X10,"));
    assert!(
        display
            .match_indices("FONT_")
            .all(|(at, _)| display[at..].starts_with("FONT_6X10")),
        "src/ui/display.rs draws in a font other than FONT_6X10"
    );
}

#[test]
fn renode_glyph_table_matches_the_firmware_font() {
    let expected = table();
    if std::env::var_os("UPDATE_OLED_FONT").is_some() {
        std::fs::write(TABLE, &expected).expect("write renode/oled-font-6x10.txt");
    }
    let actual = std::fs::read_to_string(TABLE).unwrap_or_default();
    assert!(
        actual == expected,
        "renode/oled-font-6x10.txt does not match FONT_6X10; rewrite it with \
         `UPDATE_OLED_FONT=1 cargo test --locked --test oled_font`"
    );
}

#[test]
fn every_glyph_is_distinct_so_text_reads_back_unambiguously() {
    let table = table();
    let mut seen = std::collections::HashMap::new();
    for line in table.lines().filter(|line| !line.starts_with('#')) {
        let (code, rows) = line.split_at(2);
        if let Some(other) = seen.insert(rows.to_owned(), code.to_owned()) {
            panic!("glyphs {other} and {code} have the same pixels");
        }
    }
    assert_eq!(seen.len(), 0x7E - 0x20 + 1);
}
